/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package event.service;

import org.junit.Test;
import static org.junit.Assert.*;

public class EventServiceTest {
    @Test public void testAppHasAGreeting() {
        EventService classUnderTest = new EventService();
    }
}
